[tool.poetry]
name = "py-banc-de-test"
version = "0.1.0"
description = ""
authors = ["rynerd <martin.luthi@heig-vd.ch>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
