[tool.poetry]
name = "labo-python-pandas"
version = "0.1.0"
description = "Labo"
authors = ["Yves Chevallier <yves.chevallier@heig-vd.ch>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11.2"
jupyter = "^1.1.1"
matplotlib = "^3.9.2"
notebook = "^7.2.2"
numpy = "^2.1.3"
seaborn = "^0.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
