[tool.poetry]
name = "testbench"
version = "0.1.0"
description = ""
authors = ["rynerd <martin.luthi@heig-vd.ch>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.7"
pyvisa = "^1.14.1"
pyvisa-py = "^0.7.2"
zeroconf = "^0.136.2"
psutil = "^6.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
