from testbench.interface.Agilent_GenFct import Agilent33220A
Genfct = Agilent33220A("10.192.79.15")
Genfct.connect()
print(Genfct.get_id())
Genfct.set_amplitude(18)
Genfct.set_frequency(30000000)
Genfct.set_waveform("SIN")
Genfct.set_offset(1)
Genfct.ActiveOutput()
print(Genfct.get_amplitude())
print(Genfct.get_frequency())
print(Genfct.get_waveform())
print(Genfct.get_offset())
print(Genfct.get_output_status())