name: Execute notebook

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Check file existence"
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "notebook.ipynb, requirements.txt"
    - name: Install packages
      if: steps.check_files.outputs.files_exists == 'true'
      run: |
        sudo apt-get install pandoc
        sudo apt-get install texlive-xetex texlive-fonts-recommended
    - name: Set up Python
      if: steps.check_files.outputs.files_exists == 'true'
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      if: steps.check_files.outputs.files_exists == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build notebook
      if: steps.check_files.outputs.files_exists == 'true'
      run: |
        mkdir -p artifacts
        jupyter nbconvert --to notebook --inplace --execute notebook.ipynb
        jupyter nbconvert --to pdf notebook.ipynb
        cp notebook.pdf artifacts
    - uses: actions/upload-artifact@master
      if: steps.check_files.outputs.files_exists == 'true'
      with:
        name: output
        path: artifacts
